In [1]:
%cd ..

C:\Users\RONALD\RimacProjects\coe-iaaa-kfp-pipelines-executions

In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
from aikfp.ingestamg_simulation import *
pd.set_option('display.max_columns',None)

In [5]:
df_train,df_prod=read_datasets('churn-empresas')

In [ ]:
ml=automl_training('churn-empresas',df_train.sample(22000))

In [111]:
mg=save_metadata_mg_exp('churn-empresas',df_prod,ml)

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

,name_classes,metric,value,type_metric,cer_id_ramo,cutoff,percentil,id_modelo,source,id_execution_mg
0,0,recall,0.977502,performance_by_all,all,100,all,271908884558341,kf_training,2022-07-10 15:08:00
1,0,precision,0.759870,performance_by_all,all,100,all,271908884558341,kf_training,2022-07-10 15:08:00
2,0,f1_score,0.855055,performance_by_all,all,100,all,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,cutoff,cer_id_ramo,value,percentil,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:00,kf_training,100,all,0.977502,all,recall,per_fuga_empresas_cls_prob_0,performance_by_all
1,271908884558341,2022-07-10 15:08:00,kf_training,100,all,0.759870,all,precision,per_fuga_empresas_cls_prob_0,performance_by_all
2,271908884558341,2022-07-10 15:08:00,kf_training,100,all,0.855055,all,f1_score,per_fuga_empresas_cls_prob_0,performance_by_all

,feature,cer_id_ramo,name_classes,value,type_metric,metric,id_modelo,source,id_execution_mg
0,ext_sector_empresa,all,per_fuga_empresas_cls_prob_0,0.005695,explainer_by_all,shap_abs,271908884558341,kf_training,2022-07-10 15:08:00
1,id_producto,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_training,2022-07-10 15:08:00
2,des_tamano_empresa_2,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:00,kf_training,ext_sector_empresa,all,0.005695,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:00,kf_training,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:00,kf_training,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,name_classes,id_modelo,source,id_execution_mg
0,0.350637,0.308197,-0.040989,-0.173557,-0.088609,0.018173,0.104466,-0.023192,-0.114276,0.003702,per_fuga_empresas_cls_prob_0,271908884558341,kf_training,2022-07-10 15:08:00
1,0.350637,0.308197,0.040008,0.144252,0.146258,-0.070999,-0.017251,-0.023192,-0.084495,0.005906,per_fuga_empresas_cls_prob_0,271908884558341,kf_training,2022-07-10 15:08:00
2,-0.327192,0.308197,0.168346,0.144252,-0.088609,-0.033338,-0.109579,-0.023192,0.169615,0.065289,per_fuga_empresas_cls_prob_0,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,feature_8,feature_4,feature_3,feature_5,feature_6,feature_2,name_classes,feature_7,feature_0,feature_1,feature_9
0,271908884558341,2022-07-10 15:08:00,kf_training,-0.114276,-0.088609,-0.173557,0.018173,0.104466,-0.040989,per_fuga_empresas_cls_prob_0,-0.023192,0.350637,0.308197,0.003702
1,271908884558341,2022-07-10 15:08:00,kf_training,-0.084495,0.146258,0.144252,-0.070999,-0.017251,0.040008,per_fuga_empresas_cls_prob_0,-0.023192,0.350637,0.308197,0.005906
2,271908884558341,2022-07-10 15:08:00,kf_training,0.169615,-0.088609,0.144252,-0.033338,-0.109579,0.168346,per_fuga_empresas_cls_prob_0,-0.023192,-0.327192,0.308197,0.065289

divide by zero encountered in true_divide

,name_classes,group_feature,value,feature,flg_target,metric,type_metric,id_modelo,source,id_execution_mg
0,per_fuga_empresas_cls_prob_0,AGROINDUSTRIA Y GANADERIA,0.728938,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_training,2022-07-10 15:08:00
1,per_fuga_empresas_cls_prob_0,COMERCIO MAYORISTA,0.763610,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_training,2022-07-10 15:08:00
2,per_fuga_empresas_cls_prob_0,CONSTRUCCION,0.711354,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,feature,value,metric,name_classes,flg_target,group_feature,type_metric
0,271908884558341,2022-07-10 15:08:00,kf_training,ext_sector_empresa,0.728938,WG,per_fuga_empresas_cls_prob_0,name_target,AGROINDUSTRIA Y GANADERIA,report_general
1,271908884558341,2022-07-10 15:08:00,kf_training,ext_sector_empresa,0.763610,WG,per_fuga_empresas_cls_prob_0,name_target,COMERCIO MAYORISTA,report_general
2,271908884558341,2022-07-10 15:08:00,kf_training,ext_sector_empresa,0.711354,WG,per_fuga_empresas_cls_prob_0,name_target,CONSTRUCCION,report_general

,feature,metric,value,type_metric,id_modelo,source,id_execution_mg
0,cal_cpp,hist_ref_0,0.102793,drift_bins,271908884558341,kf_training,2022-07-10 15:08:00
1,cal_cpp_dif_12m,hist_ref_0,0.000719,drift_bins,271908884558341,kf_training,2022-07-10 15:08:00
2,cal_cpp_dif_1m,hist_ref_0,0.001367,drift_bins,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,feature,metric,value,type_metric
0,271908884558341,2022-07-10 15:08:00,kf_training,cal_cpp,hist_ref_0,0.102793,drift_bins
1,271908884558341,2022-07-10 15:08:00,kf_training,cal_cpp_dif_12m,hist_ref_0,0.000719,drift_bins
2,271908884558341,2022-07-10 15:08:00,kf_training,cal_cpp_dif_1m,hist_ref_0,0.001367,drift_bins

   iteration  training  validation        id_modelo
0          0  0.570695    0.570659  271908884558341
1          1  0.570038    0.570058  271908884558341
2          2  0.569903    0.569955  271908884558341

         id_modelo  training  validation  iteration
0  271908884558341  0.570695    0.570659          0
1  271908884558341  0.570038    0.570058          1
2  271908884558341  0.569903    0.569955          2

   trial state_trial  value_trial      parameter       value        id_modelo
0      0    COMPLETE     0.570806  params_cat_l2  327.301169  271908884558341
1      1    COMPLETE     0.570806  params_cat_l2  235.251851  271908884558341
2      2    COMPLETE     0.474910  params_cat_l2  221.908527  271908884558341

         id_modelo      parameter  trial  value_trial state_trial       value
0  271908884558341  params_cat_l2      0     0.570806    COMPLETE  327.301169
1  271908884558341  params_cat_l2      1     0.570806    COMPLETE  235.251851
2  271908884558341  params_cat_l2      2     0.474910    COMPLETE  221.908527

,name_project,name_subproject,task,type_model,version,selection_method,cfg_parameters,name_target,name_prediction,id_features,obs_features,kpi_features,subpoblation_features,subpoblation_values,cat_features,cont_features,text_features,steps,preprocess,tuning,training,id_entrenamiento,id_modelo,workflow,n_classes,periodo_min,periodo_max,n_rows,evol_features,sub_cols,list_of_parameters,fix_selection_method,use_fs,fs_treshold,fs_mode,use_hpo,n_trials,supoblation_values,name_features,n_features,n_ids,n_obs,obj,metric,n_used_features,steps_cat_preprocess,steps_cont_preprocess,preprocess_constants,n_folds,strategy_fold,best_features
0,coe-iaaa-iniciatives-empresas-fuga,scoring,classification,LGB,0.1.0,stratified,"{'n_estimators': 1000, 'l_rate': 0.09, 'early_...",target,per_fuga_empresas_cls,"['id_contratante', 'id_poliza', 'ramo', 'perio...","['id_contratante', 'periodo']",ctd_operaciones,cer_id_ramo,"['AX-SOAT', 'AX-VEHI']","['ext_sector_empresa', 'id_producto', 'des_tam...","['ctd_operaciones', 'mto_prima_anual_usd_3a', ...",[],"{'use_fs': False, 'use_hpo': True, 'use_traini...","{'steps_cat_preprocess': ['null', 'le'], 'step...",{'n_trials': 10},{'n_folds': 0},2022-07-10 13:07:40,271908884558341,gs://ue4_ndlk_nonprod_stg_gcs_iadev_adsto/tmp/...,2,2021-03-01,2021-06-01,32000,periodo,"['per_fuga_empresas_cls_prob_0', 'per_fuga_emp...","['params_bagging_seed', 'params_cat_l2', 'para...",no,no,1,n_features,si,10,"['AX-SOAT', 'AX-VEHI', 'nan']","['ext_sector_empresa', 'id_producto', 'des_tam...",118,32000,17016,binary,binary_logloss,118,"['null', 'le']",['skip'],"{'num_fill_null': 'mean', 'num_outlier_range':...",0,no_folds,mto_prima_anual_usd_1a

,id_modelo,obj,steps_cat_preprocess,name_features,name_subproject,name_target,metric,tuning,id_entrenamiento,training,strategy_fold,version,steps,use_hpo,name_prediction,task,cat_features,workflow,fix_selection_method,n_rows,n_classes,type_model,selection_method,n_ids,n_obs,n_folds,n_trials,n_features,id_features,fs_mode,steps_cont_preprocess,preprocess,preprocess_constants,periodo_max,subpoblation_features,cont_features,text_features,evol_features,cfg_parameters,supoblation_values,subpoblation_values,periodo_min,kpi_features,obs_features,use_fs,n_used_features,list_of_parameters,fs_treshold,sub_cols,name_project,best_features
0,271908884558341,binary,"['null', 'le']","['ext_sector_empresa', 'id_producto', 'des_tam...",scoring,target,binary_logloss,{'n_trials': 10},2022-07-10 13:07:40,{'n_folds': 0},no_folds,0.1.0,"{'use_fs': False, 'use_hpo': True, 'use_traini...",si,per_fuga_empresas_cls,classification,"['ext_sector_empresa', 'id_producto', 'des_tam...",gs://ue4_ndlk_nonprod_stg_gcs_iadev_adsto/tmp/...,no,32000,2,LGB,stratified,32000,17016,0,10,118,"['id_contratante', 'id_poliza', 'ramo', 'perio...",n_features,['skip'],"{'steps_cat_preprocess': ['null', 'le'], 'step...","{'num_fill_null': 'mean', 'num_outlier_range':...",2021-06-01,cer_id_ramo,"['ctd_operaciones', 'mto_prima_anual_usd_3a', ...",[],periodo,"{'n_estimators': 1000, 'l_rate': 0.09, 'early_...","['AX-SOAT', 'AX-VEHI', 'nan']","['AX-SOAT', 'AX-VEHI']",2021-03-01,ctd_operaciones,"['id_contratante', 'periodo']",no,118,"['params_bagging_seed', 'params_cat_l2', 'para...",1,"['per_fuga_empresas_cls_prob_0', 'per_fuga_emp...",coe-iaaa-iniciatives-empresas-fuga,mto_prima_anual_usd_1a

,cpu_usage_m_1,cpu_usage_0,cpu_usage_s_1,memory_usage_available,memory_usage_total,message,periodo,time_acum,id_modelo
0,0.000,0.000,0.0,1.668633e+09,8.350593e+09,Cfg de entrenamiento creado,2022-07-09,449368,271908884558341
1,0.125,0.125,0.0,1.507066e+09,8.350593e+09,Cfg de entrenamiento creado,2022-07-09,578163,271908884558341
2,0.125,0.125,0.0,1.498087e+09,8.350593e+09,"Tipo_Preprocess: cat - ['null', 'le'], cont - ...",2022-07-09,578459,271908884558341

,id_modelo,message,memory_usage_total,cpu_usage_0,periodo,cpu_usage_m_1,memory_usage_available,cpu_usage_s_1,time_acum
0,271908884558341,Cfg de entrenamiento creado,8.350593e+09,0.000,2022-07-09,0.000,1.668633e+09,0.0,449368
1,271908884558341,Cfg de entrenamiento creado,8.350593e+09,0.125,2022-07-09,0.125,1.507066e+09,0.0,578163
2,271908884558341,"Tipo_Preprocess: cat - ['null', 'le'], cont - ...",8.350593e+09,0.125,2022-07-09,0.125,1.498087e+09,0.0,578459

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:00,kf_training,ext_sector_empresa,all,0.005695,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:00,kf_training,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:00,kf_training,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,log_loss,accuracy,roc_auc_score,gini,precision,recall,f1_score,fi_shap_0,fi_shap_0_5,feature_drift,target_drift,prediction_drift,kpi_mae,cpu_usage_percent,ram_usage_percent,id_modelo,source,id_execution_mg
0,0.474188,0.754,0.795137,0.590275,0.694791,0.543854,0.521319,0.228814,0.008475,0.110169,0.292042,0.271026,0.221518,1.229067,0.171082,271908884558341,kf_training,2022-07-10 15:08:00

,id_modelo,id_execution_mg,source,precision,feature_drift,fi_shap_0_5,log_loss,target_drift,recall,accuracy,ram_usage_percent,gini,kpi_mae,f1_score,cpu_usage_percent,fi_shap_0,roc_auc_score,prediction_drift
0,271908884558341,2022-07-10 15:08:00,kf_training,0.694791,0.110169,0.008475,0.474188,0.292042,0.543854,0.754,0.171082,0.590275,0.221518,0.521319,1.229067,0.228814,0.795137,0.271026

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

,name_classes,metric,value,type_metric,cer_id_ramo,cutoff,percentil,id_modelo,source,id_execution_mg
0,0,recall,0.973971,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:24
1,0,precision,0.749073,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:24
2,0,f1_score,0.846845,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,cutoff,cer_id_ramo,value,percentil,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:24,kf_predict,100,all,0.973971,all,recall,per_fuga_empresas_cls_prob_0,performance_by_all
1,271908884558341,2022-07-10 15:08:24,kf_predict,100,all,0.749073,all,precision,per_fuga_empresas_cls_prob_0,performance_by_all
2,271908884558341,2022-07-10 15:08:24,kf_predict,100,all,0.846845,all,f1_score,per_fuga_empresas_cls_prob_0,performance_by_all

,feature,cer_id_ramo,name_classes,value,type_metric,metric,id_modelo,source,id_execution_mg
0,ext_sector_empresa,all,per_fuga_empresas_cls_prob_0,0.005716,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:24
1,id_producto,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:24
2,des_tamano_empresa_2,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:24,kf_predict,ext_sector_empresa,all,0.005716,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:24,kf_predict,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:24,kf_predict,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,name_classes,id_modelo,source,id_execution_mg
0,-0.536851,-0.3381,-0.048765,0.144252,-0.030981,0.005423,0.016618,0.076030,0.169615,0.005150,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:24
1,0.350637,-0.3381,0.168346,0.004370,0.109074,0.018173,-0.017251,-0.090838,-0.084495,0.065289,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:24
2,-0.536851,-0.3381,0.025332,0.144252,0.109074,0.005423,-0.085538,0.076030,0.169615,-0.007703,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,feature_8,feature_4,feature_3,feature_5,feature_6,feature_2,name_classes,feature_7,feature_0,feature_1,feature_9
0,271908884558341,2022-07-10 15:08:24,kf_predict,0.169615,-0.030981,0.144252,0.005423,0.016618,-0.048765,per_fuga_empresas_cls_prob_0,0.076030,-0.536851,-0.3381,0.005150
1,271908884558341,2022-07-10 15:08:24,kf_predict,-0.084495,0.109074,0.004370,0.018173,-0.017251,0.168346,per_fuga_empresas_cls_prob_0,-0.090838,0.350637,-0.3381,0.065289
2,271908884558341,2022-07-10 15:08:24,kf_predict,0.169615,0.109074,0.144252,0.005423,-0.085538,0.025332,per_fuga_empresas_cls_prob_0,0.076030,-0.536851,-0.3381,-0.007703

divide by zero encountered in true_divide

,name_classes,group_feature,value,feature,flg_target,metric,type_metric,id_modelo,source,id_execution_mg
0,per_fuga_empresas_cls_prob_0,AGROINDUSTRIA Y GANADERIA,0.779221,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:24
1,per_fuga_empresas_cls_prob_0,AUTOMOTRIZ,0.684426,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:24
2,per_fuga_empresas_cls_prob_0,COMERCIO MAYORISTA,0.720056,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,feature,value,metric,name_classes,flg_target,group_feature,type_metric
0,271908884558341,2022-07-10 15:08:24,kf_predict,ext_sector_empresa,0.779221,WG,per_fuga_empresas_cls_prob_0,name_target,AGROINDUSTRIA Y GANADERIA,report_general
1,271908884558341,2022-07-10 15:08:24,kf_predict,ext_sector_empresa,0.684426,WG,per_fuga_empresas_cls_prob_0,name_target,AUTOMOTRIZ,report_general
2,271908884558341,2022-07-10 15:08:24,kf_predict,ext_sector_empresa,0.720056,WG,per_fuga_empresas_cls_prob_0,name_target,COMERCIO MAYORISTA,report_general

,feature,metric,value,type_metric,id_modelo,source,id_execution_mg
0,cal_cpp,hist_ref_0,0.096450,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:24
1,cal_cpp_dif_12m,hist_ref_0,0.000592,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:24
2,cal_cpp_dif_1m,hist_ref_0,0.001160,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,feature,metric,value,type_metric
0,271908884558341,2022-07-10 15:08:24,kf_predict,cal_cpp,hist_ref_0,0.096450,drift_bins
1,271908884558341,2022-07-10 15:08:24,kf_predict,cal_cpp_dif_12m,hist_ref_0,0.000592,drift_bins
2,271908884558341,2022-07-10 15:08:24,kf_predict,cal_cpp_dif_1m,hist_ref_0,0.001160,drift_bins

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:24,kf_predict,ext_sector_empresa,all,0.005716,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:24,kf_predict,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:24,kf_predict,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,log_loss,accuracy,roc_auc_score,gini,precision,recall,f1_score,fi_shap_0,fi_shap_0_5,feature_drift,target_drift,prediction_drift,kpi_mae,cpu_usage_percent,ram_usage_percent,id_modelo,source,id_execution_mg
0,0.482053,0.7442,0.802867,0.605733,0.705485,0.554528,0.535612,0.228814,0.008475,0.220339,0.243958,0.656524,0.239727,NaN,NaN,271908884558341,kf_predict,2022-07-10 15:08:24

,id_modelo,id_execution_mg,source,precision,feature_drift,fi_shap_0_5,log_loss,target_drift,recall,accuracy,ram_usage_percent,gini,kpi_mae,f1_score,cpu_usage_percent,fi_shap_0,roc_auc_score,prediction_drift
0,271908884558341,2022-07-10 15:08:24,kf_predict,0.705485,0.220339,0.008475,0.482053,0.243958,0.554528,0.7442,NaN,0.605733,0.239727,0.535612,NaN,0.228814,0.802867,0.656524

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

,name_classes,metric,value,type_metric,cer_id_ramo,cutoff,percentil,id_modelo,source,id_execution_mg
0,0,recall,0.978517,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:49
1,0,precision,0.749581,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:49
2,0,f1_score,0.848884,performance_by_all,all,100,all,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,cutoff,cer_id_ramo,value,percentil,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:49,kf_predict,100,all,0.978517,all,recall,per_fuga_empresas_cls_prob_0,performance_by_all
1,271908884558341,2022-07-10 15:08:49,kf_predict,100,all,0.749581,all,precision,per_fuga_empresas_cls_prob_0,performance_by_all
2,271908884558341,2022-07-10 15:08:49,kf_predict,100,all,0.848884,all,f1_score,per_fuga_empresas_cls_prob_0,performance_by_all

,feature,cer_id_ramo,name_classes,value,type_metric,metric,id_modelo,source,id_execution_mg
0,ext_sector_empresa,all,per_fuga_empresas_cls_prob_0,0.005748,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:49
1,id_producto,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:49
2,des_tamano_empresa_2,all,per_fuga_empresas_cls_prob_0,0.000000,explainer_by_all,shap_abs,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:49,kf_predict,ext_sector_empresa,all,0.005748,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:49,kf_predict,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:49,kf_predict,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,name_classes,id_modelo,source,id_execution_mg
0,-0.553436,0.308197,-0.040989,0.144252,0.109074,-0.070999,-0.109579,0.07603,-0.022027,0.003702,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:49
1,0.350637,0.308197,0.098466,0.144252,-0.030981,-0.033338,-0.017251,0.07603,0.169615,0.001089,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:49
2,-0.536851,-0.338100,0.168346,0.144252,0.088630,-0.033338,-0.109579,0.07603,0.169615,0.065289,per_fuga_empresas_cls_prob_0,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,feature_8,feature_4,feature_3,feature_5,feature_6,feature_2,name_classes,feature_7,feature_0,feature_1,feature_9
0,271908884558341,2022-07-10 15:08:49,kf_predict,-0.022027,0.109074,0.144252,-0.070999,-0.109579,-0.040989,per_fuga_empresas_cls_prob_0,0.07603,-0.553436,0.308197,0.003702
1,271908884558341,2022-07-10 15:08:49,kf_predict,0.169615,-0.030981,0.144252,-0.033338,-0.017251,0.098466,per_fuga_empresas_cls_prob_0,0.07603,0.350637,0.308197,0.001089
2,271908884558341,2022-07-10 15:08:49,kf_predict,0.169615,0.088630,0.144252,-0.033338,-0.109579,0.168346,per_fuga_empresas_cls_prob_0,0.07603,-0.536851,-0.338100,0.065289

divide by zero encountered in true_divide

,name_classes,group_feature,value,feature,flg_target,metric,type_metric,id_modelo,source,id_execution_mg
0,per_fuga_empresas_cls_prob_0,AUTOMOTRIZ,0.747899,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:49
1,per_fuga_empresas_cls_prob_0,COMERCIO MAYORISTA,0.740057,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:49
2,per_fuga_empresas_cls_prob_0,CONSTRUCCION,0.679688,ext_sector_empresa,name_target,WG,report_general,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,feature,value,metric,name_classes,flg_target,group_feature,type_metric
0,271908884558341,2022-07-10 15:08:49,kf_predict,ext_sector_empresa,0.747899,WG,per_fuga_empresas_cls_prob_0,name_target,AUTOMOTRIZ,report_general
1,271908884558341,2022-07-10 15:08:49,kf_predict,ext_sector_empresa,0.740057,WG,per_fuga_empresas_cls_prob_0,name_target,COMERCIO MAYORISTA,report_general
2,271908884558341,2022-07-10 15:08:49,kf_predict,ext_sector_empresa,0.679688,WG,per_fuga_empresas_cls_prob_0,name_target,CONSTRUCCION,report_general

,feature,metric,value,type_metric,id_modelo,source,id_execution_mg
0,cal_cpp,hist_ref_0,0.096450,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:49
1,cal_cpp_dif_12m,hist_ref_0,0.000592,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:49
2,cal_cpp_dif_1m,hist_ref_0,0.001160,drift_bins,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,feature,metric,value,type_metric
0,271908884558341,2022-07-10 15:08:49,kf_predict,cal_cpp,hist_ref_0,0.096450,drift_bins
1,271908884558341,2022-07-10 15:08:49,kf_predict,cal_cpp_dif_12m,hist_ref_0,0.000592,drift_bins
2,271908884558341,2022-07-10 15:08:49,kf_predict,cal_cpp_dif_1m,hist_ref_0,0.001160,drift_bins

,id_modelo,id_execution_mg,source,feature,cer_id_ramo,value,metric,name_classes,type_metric
0,271908884558341,2022-07-10 15:08:49,kf_predict,ext_sector_empresa,all,0.005748,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
1,271908884558341,2022-07-10 15:08:49,kf_predict,id_producto,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all
2,271908884558341,2022-07-10 15:08:49,kf_predict,des_tamano_empresa_2,all,0.000000,shap_abs,per_fuga_empresas_cls_prob_0,explainer_by_all

,log_loss,accuracy,roc_auc_score,gini,precision,recall,f1_score,fi_shap_0,fi_shap_0_5,feature_drift,target_drift,prediction_drift,kpi_mae,cpu_usage_percent,ram_usage_percent,id_modelo,source,id_execution_mg
0,0.480683,0.7454,0.79698,0.593959,0.704138,0.545536,0.520572,0.228814,0.008475,0.20339,0.022565,0.740144,0.23034,NaN,NaN,271908884558341,kf_predict,2022-07-10 15:08:49

,id_modelo,id_execution_mg,source,precision,feature_drift,fi_shap_0_5,log_loss,target_drift,recall,accuracy,ram_usage_percent,gini,kpi_mae,f1_score,cpu_usage_percent,fi_shap_0,roc_auc_score,prediction_drift
0,271908884558341,2022-07-10 15:08:49,kf_predict,0.704138,0.20339,0.008475,0.480683,0.022565,0.545536,0.7454,NaN,0.593959,0.23034,0.520572,NaN,0.228814,0.79698,0.740144